FROM nginx:stable-alpine

RUN apk add --no-cache tzdata && \
  rm -rf /var/cache/apk/* && \
  rm -v /etc/nginx/nginx.conf

ADD nginx.conf /etc/nginx/nginx.conf
ADD entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

ENTRYPOINT /entrypoint.sh